export const FROM_CITY_TO_COORDS = 'FROM_CITY_TO_COORDS';

export const FETCH_CREATE_JOURNEY = 'FETCH_CREATE_JOURNEY';
export const FETCH_FIND_ALL_JOURNEY = 'FETCH_FIND_ALL_JOURNEY';
export const FETCH_FIND_QUERY_JOURNEY = 'FETCH_FIND_QUERY_JOURNEY';

export const FETCH_SUBMIT_CREATED_JOURNEY = 'FETCH_SUBMIT_CREATED_JOURNEY';
export const FETCH_MODAL_USER_INFO = 'FETCH_MODAL_USER_INFO';
export const FETCH_MODAL_USER_REQUEST_TRIP = 'FETCH_MODAL_USER_REQUEST_TRIP';



// AUTH
export const AUTH_SUCCESSFULLY = 'AUTH_SUCCESSFULLY';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CHANGE_DATA = 'CHANGE_DATA'
export const CHANGE_ERROR = 'CHANGE_ERROR';
export const ADD_PROFILE_PICTURE = 'ADD_PROFILE_PICTURE'
export const INIT_PROFILE = 'INIT_PROFILE'
export const SIGNUP_SUCCESSFULLY = 'SIGNUP_SUCCESSFULLY';


//MESSAGE

export const SEND_MESSAGE = 'SEND_MESSAGE'

//TRIPS
export const INIT_TRIPS = 'INIT_TRIPS'
export const DELETE_TRIPS ='DELETE_TRIPS'
export const ADD_TRIPS = 'ADD_TRIPS'
export const EDIT_MY_TRIP = 'EDIT_MY_TRIP'
