export const FROM_CITY_TO_COORDS = 'FROM_CITY_TO_COORDS';

export const FETCH_CREATE_JOURNEY = 'FETCH_CREATE_JOURNEY';
export const FETCH_FIND_ALL_JOURNEY = 'FETCH_FIND_ALL_JOURNEY';
export const FETCH_DOG = 'FETCH_DOG';
export const FETCH_KEK = 'FETCH_KEK';

export const SAGA_DOG_TAKE_EVERY = 'SAGA_DOG_TAKE_EVERY';

// AUTH
export const AUTH_SUCCESSFULLY = 'AUTH_SUCCESSFULLY';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';


//CHAT
export const START_CHAT = 'START_CHAT'
export const SEND_MESSAGE = 'SEND_MESSAGE'

//TRIPS
export const INIT_TRIPS = 'INIT_TRIPS'
